set-option -sa terminal-overrides ",xterm*:Tc"
set -g default-terminal "screen-256color"
set -g status-right "%H:%M %d-%b-%y"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.tmux/plugins/tpm/tpm'

unbind C-b # Unbind the default prefix
set -g prefix C-Space # Set new prefix to Ctrl+Space
bind C-Space send-prefix # Allow Ctrl+Space to be sent to applications

# set vi-mode
set-window-option -g mode-keys vi
# enable mouse for resizing panes
set -g mouse on

# cwd on split
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

#Allow multiple commands to be entered without pressing the prefix-key again in the specified time milliseconds
set -g repeat-time 600

# set status bar color
set -g status-bg '#2b3339'
set -g status-fg '#d3c6aa'
# set-window-option -g window-status-current-style bg=red

# set empty right status bar
set -g status-right ""

# set window colors
setw -g window-status-current-style fg=black,bg=green
set -g window-status-current-format "#I-#W"
set -g window-status-format "#I-#W"


# set statusbar on top
# set -g status-position top
# disable pane border
set-window-option -g pane-border-status off

# resize on ctrl arrow keys
bind -r C-Up resize-pane -U 2
bind -r C-Down resize-pane -D 2
bind -r C-Left resize-pane -L 2
bind -r C-Right resize-pane -R 2

# split with ctrl+w + s/v
bind-key C-w switch-client -T split-keys
bind-key -T split-keys s split-window -v
bind-key -T split-keys v split-window -h

# start window numbering at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
