local wk = require("which-key")

wk.add({
	{ "<leader>c", "<cmd>Bwipeout!<cr>", desc = "close buffer" },
	{ "<leader>d", group = "debugger" },
	{ "<leader>dr", "<cmd>lua require('dapui').open({reset = true})<cr>", desc = "reset ui" },
	{ "<leader>ds", "<cmd>DapContinue<cr>", desc = "start/continue" },
	{ "<leader>dt", "<cmd>DapToggleBreakpoint<cr>", desc = "toggle breakpoint" },
	{ "<leader>du", "<cmd>lua require('dapui').toggle()<cr>", desc = "toggle dapUI" },
	{ "<leader>dx", "<cmd>DapTerminate<cr>", desc = "terminate" },
	{ "<leader>l", group = "lsp" },
	{ "<leader>lF", "<cmd>lua vim.lsp.buf.format()<cr>", desc = "format document(lsp)" },
	{ "<leader>la", "<cmd>lua vim.lsp.buf.code_action()<cr>", desc = "peform code action" },
	{ "<leader>ld", "<cmd>lua vim.diagnostic.open_float()<cr>", desc = "show diagnostics" },
	{ "<leader>lf", "<cmd>lua require('conform').format()<cr>", desc = "format document" },
	{ "<leader>li", "<cmd>LspInfo<cr>", desc = "show lsp info" },
	{ "<leader>lr", "<cmd>lua vim.lsp.buf.rename()<cr>", desc = "rename symbol" },
	{ "<leader>r", "<cmd>Telescope file_browser<cr>", desc = "file_browser" },
	{ "<leader>s", group = "search" },
	{ "<leader>sc", "<cmd>Easypick cargo_commands<cr>", desc = "search cargo command" },
	{ "<leader>sf", "<cmd>Telescope find_files<cr>", desc = "search file by name" },
	{ "<leader>sm", "<cmd>Easypick make_targets<cr>", desc = "search make target" },
	{ "<leader>sn", "<cmd>Easypick npm_scripts<cr>", desc = "search npm command" },
	{ "<leader>so", "<cmd>Telescope buffers<cr>", desc = "open buffers" },
	{ "<leader>st", "<cmd>Telescope live_grep<cr>", desc = "search file by text" },
	{ "<leader>t", group = "toggles" },
	{ "<leader>tb", "<cmd>GitBlameToggle<cr>", desc = "git blame" },
	{ "<leader>td", "<cmd>DBUIToggle<cr>", desc = "database UI" },
	{ "<leader>tt", "<cmd>lua require('trouble').toggle()<cr>", desc = "trouble" },
})
